# syntax=docker/dockerfile:1
FROM debian:10
RUN apt-get update && apt-get -y upgrade
RUN apt-get -y install libmariadb-dev-compat libpcap-dev libnet-dev libconfig-dev libsystemd-dev cmake
RUN apt-get -y install git-buildpackage python3-pip
RUN pip3 install cpplint
