# syntax=docker/dockerfile:1
FROM centos:7
#RUN yum install -y 'yum-command(config-manager)'
RUN yum -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
#RUN yum config-manager --set-enabled powertools
RUN yum -y update
RUN yum -y group install "Development Tools"
RUN yum -y install cmake systemd-rpm-macros libpcap-devel libnet-devel libconfig-devel mariadb-connector-c-devel
RUN yum -y install python2-pip python3-pip
RUN pip3 install cpplint
