trigger:
  branches:
    include:
    - main
    - releases/*
  tags:
    include:
    - v*

variables:
  System.Debug: false

stages:
- stage: Build

  jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'

    strategy:
      matrix:
        centos8:
          containerImage: stuwilkins/arptools-build-centos8:latest
          pkg_type: redhat
          rpmrelease: centos8
          cmake: cmake
        centos7:
          containerImage: stuwilkins/arptools-build-centos7:latest
          pkg_type: redhat
          rpmrelease: centos7
          cmake: cmake3
        deb10:
          containerImage: stuwilkins/arptools-build-deb10:latest
          debrelease: debian10
          pkg_type: debian
          cmake: cmake

    container:
      image: $[ variables['containerImage'] ]

    steps:
    - script: |
        set -e
        mkdir build
        cd build
        $(cmake) ..
      displayName: Run CMAKE

    - script: |
        set -e
        cd build
        VERBOSE=1 make
      displayName: Build

    - script: |
        GITDESC=$(git describe --abbrev=0)
        VERSION=$(git describe --abbrev=0 | sed -En 's/v([0-9]+\.)([0-9]+\.)?([0-9]+)/\1\2\3/p')
        echo "##vso[task.setvariable variable=gitdesc]$GITDESC"
        echo "##vso[task.setvariable variable=gitversion]$VERSION"
        echo "##[debug] GITDESC = $GITDESC"
        echo "##[debug] VERSION = $VERSION"
      displayName: Set Git Describe to Variable

    - script: |
        set -e
        mkdir -p build
        gbp buildpackage \
          --git-ignore-new \
          --git-ignore-branch \
          -uc -us \
          --git-export-dir=build \
          --git-tarball-dir=build \
          --git-upstream-tree=main
        old_debfile=$(ls -1 build/arptools_*.deb | head -1)
        new_debfile=$(echo ${old_debfile} | sed "s/\.deb/-$(debrelease).deb/")
        mv "${old_debfile}" "${new_debfile}"
        echo "##vso[task.setvariable variable=releasefile]${new_debfile}"
        echo "##[debug] old_debfile = ${old_debfile}"
        echo "##[debug] new_debfile = ${new_debfile}"
        echo "##[debug] gitdesc = $(gitdesc)"
      displayName: 'Build Debian Package'
      condition: and(succeeded(), eq(variables.pkg_type, 'debian'))

    - task: CopyFiles@2
      inputs:
        targetFolder: '$(Build.ArtifactStagingDirectory)'
        contents: 'build/arptools_*.deb'
        flattenFolders: true
      condition: and(succeeded(), eq(variables.pkg_type, 'debian'))

    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: packages
      displayName: Publish Debian Packages
      condition: and(succeeded(), eq(variables.pkg_type, 'debian'))

    - script: |
        set -e
        RPMDIR="`pwd`/rpmbuild"
        echo $RPMDIR
        SOURCES=${RPMDIR}/SOURCES
        mkdir -p ${SOURCES}
        git archive --format=tar \
          --prefix=arptools-$(gitversion)/ \
          --output=${SOURCES}/arptools-v$(gitversion).tar.gz \
          HEAD
        rpmbuild -bb --define "_topdir ${RPMDIR}" --define "version $(gitversion)" arptools.spec
      displayName: 'Build rpm Package'
      condition: and(succeeded(), eq(variables.pkg_type, 'redhat'))

    - task: CopyFiles@2
      inputs:
        targetFolder: '$(Build.ArtifactStagingDirectory)'
        contents: rpmbuild/RPMS/x86_64/*
        flattenFolders: true
      condition: and(succeeded(), eq(variables.pkg_type, 'redhat'))

    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: packages
      displayName: Publish RedHat Packages
      condition: and(succeeded(), eq(variables.pkg_type, 'redhat'))

  - job: Publish
    dependsOn: Build
    condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/v')
    steps:
      - script: |
          GITDESC=$(git describe --abbrev=0)
          echo "##vso[task.setvariable variable=gitdesc]$GITDESC"
          echo "##[debug] GITDESC = $GITDESC"
        displayName: Set Git Describe to Variable
      - task: DownloadBuildArtifacts@0
        inputs:
          buildType: 'current'
          downloadType: 'single'
          artifactName: 'packages'
          downloadPath: '$(System.ArtifactsDirectory)'
        displayName: Download Packages
      - task: GithubRelease@0
        inputs:
          gitHubConnection: github.com_stuwilkins
          repositoryName: NSLS-II/arptools
          assets: '$(System.ArtifactsDirectory)/**/*'
          action: edit
          target: '$(Build.SourceVersion)'
          tag: $(gitdesc)
          addChangeLog: false
          assetUploadMode: replace
        displayName: 'Attach package to release'
