# syntax=docker/dockerfile:1
FROM debian:10
RUN dpkg --add-architecture armhf
RUN apt-get update && apt-get -y upgrade
RUN apt-get -y install build-essential crossbuild-essential-armhf cmake
RUN apt-get -y install libmariadb-dev-compat:armhf libpcap0.8-dev:armhf libnet1-dev:armhf libconfig-dev:armhf libsystemd-dev:armhf
RUN apt-get -y install git-buildpackage python3-pip systemd
RUN pip3 install cpplint
